In [3]:
import numpy as np
m = np.random.randint(1, 10, (4, 6))
print(m)

[[3 1 1 4 5 5]
 [2 3 3 8 9 2]
 [9 9 4 5 2 6]
 [9 2 7 5 7 3]]


In [4]:
m

array([[3, 1, 1, 4, 5, 5],
       [2, 3, 3, 8, 9, 2],
       [9, 9, 4, 5, 2, 6],
       [9, 2, 7, 5, 7, 3]], dtype=int32)

In [5]:
len(m) #always tells us the number of rows, not columns

4

In [7]:
m.shape #prints the dimension of array

(4, 6)

In [8]:
m[:]

array([[3, 1, 1, 4, 5, 5],
       [2, 3, 3, 8, 9, 2],
       [9, 9, 4, 5, 2, 6],
       [9, 2, 7, 5, 7, 3]], dtype=int32)

In [12]:
m1 = np.random.randint(1, 10, (9, 9))
print(m1)

[[3 2 4 2 1 9 9 4 8]
 [9 3 6 7 8 3 3 4 4]
 [6 5 6 9 5 6 3 6 8]
 [6 7 6 3 9 9 4 5 6]
 [4 4 3 9 3 4 9 4 4]
 [6 9 5 1 2 3 2 8 2]
 [2 9 1 9 8 3 8 6 6]
 [7 6 5 8 7 8 1 7 5]
 [4 9 2 3 8 4 8 2 8]]


In [ ]:
m1[0:9:3] #start at index 0 row and then print every 3rd row until index 9

array([[3, 2, 4, 2, 1, 9, 9, 4, 8],
       [6, 7, 6, 3, 9, 9, 4, 5, 6],
       [2, 9, 1, 9, 8, 3, 8, 6, 6]], dtype=int32)

In [14]:
m1[::2]

array([[3, 2, 4, 2, 1, 9, 9, 4, 8],
       [6, 5, 6, 9, 5, 6, 3, 6, 8],
       [4, 4, 3, 9, 3, 4, 9, 4, 4],
       [2, 9, 1, 9, 8, 3, 8, 6, 6],
       [4, 9, 2, 3, 8, 4, 8, 2, 8]], dtype=int32)

In [15]:
m1[::5]

array([[3, 2, 4, 2, 1, 9, 9, 4, 8],
       [6, 9, 5, 1, 2, 3, 2, 8, 2]], dtype=int32)

In [16]:
m1[::-1]

array([[4, 9, 2, 3, 8, 4, 8, 2, 8],
       [7, 6, 5, 8, 7, 8, 1, 7, 5],
       [2, 9, 1, 9, 8, 3, 8, 6, 6],
       [6, 9, 5, 1, 2, 3, 2, 8, 2],
       [4, 4, 3, 9, 3, 4, 9, 4, 4],
       [6, 7, 6, 3, 9, 9, 4, 5, 6],
       [6, 5, 6, 9, 5, 6, 3, 6, 8],
       [9, 3, 6, 7, 8, 3, 3, 4, 4],
       [3, 2, 4, 2, 1, 9, 9, 4, 8]], dtype=int32)

In [17]:
m1[::-4]

array([[4, 9, 2, 3, 8, 4, 8, 2, 8],
       [4, 4, 3, 9, 3, 4, 9, 4, 4],
       [3, 2, 4, 2, 1, 9, 9, 4, 8]], dtype=int32)

In [18]:
my_list = [0, 1, 2, 3, 4, 5]
arr = np.array(my_list)

In [19]:
arr

array([0, 1, 2, 3, 4, 5])

In [21]:
arr.shape

(6,)

In [22]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.reshape(4,2) #this will not work because we have 6 elements in the array and we cannot reshape it to 8 elements (4*2=8) 

ValueError: cannot reshape array of size 6 into shape (4,2)

In [25]:
arr.reshape(1, 6)

array([[0, 1, 2, 3, 4, 5]])

In [26]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [27]:
m

array([[3, 1, 1, 4, 5, 5],
       [2, 3, 3, 8, 9, 2],
       [9, 9, 4, 5, 2, 6],
       [9, 2, 7, 5, 7, 3]], dtype=int32)

In [28]:
m[2, 4]

np.int32(2)

In [29]:
m[2:4]

array([[9, 9, 4, 5, 2, 6],
       [9, 2, 7, 5, 7, 3]], dtype=int32)

In [30]:
m

array([[3, 1, 1, 4, 5, 5],
       [2, 3, 3, 8, 9, 2],
       [9, 9, 4, 5, 2, 6],
       [9, 2, 7, 5, 7, 3]], dtype=int32)

In [34]:
m[:,-3:5]

array([[4, 5],
       [8, 9],
       [5, 2],
       [5, 7]], dtype=int32)

In [35]:
m1

array([[3, 2, 4, 2, 1, 9, 9, 4, 8],
       [9, 3, 6, 7, 8, 3, 3, 4, 4],
       [6, 5, 6, 9, 5, 6, 3, 6, 8],
       [6, 7, 6, 3, 9, 9, 4, 5, 6],
       [4, 4, 3, 9, 3, 4, 9, 4, 4],
       [6, 9, 5, 1, 2, 3, 2, 8, 2],
       [2, 9, 1, 9, 8, 3, 8, 6, 6],
       [7, 6, 5, 8, 7, 8, 1, 7, 5],
       [4, 9, 2, 3, 8, 4, 8, 2, 8]], dtype=int32)

In [36]:
m1[2:]

array([[6, 5, 6, 9, 5, 6, 3, 6, 8],
       [6, 7, 6, 3, 9, 9, 4, 5, 6],
       [4, 4, 3, 9, 3, 4, 9, 4, 4],
       [6, 9, 5, 1, 2, 3, 2, 8, 2],
       [2, 9, 1, 9, 8, 3, 8, 6, 6],
       [7, 6, 5, 8, 7, 8, 1, 7, 5],
       [4, 9, 2, 3, 8, 4, 8, 2, 8]], dtype=int32)

In [37]:
m1

array([[3, 2, 4, 2, 1, 9, 9, 4, 8],
       [9, 3, 6, 7, 8, 3, 3, 4, 4],
       [6, 5, 6, 9, 5, 6, 3, 6, 8],
       [6, 7, 6, 3, 9, 9, 4, 5, 6],
       [4, 4, 3, 9, 3, 4, 9, 4, 4],
       [6, 9, 5, 1, 2, 3, 2, 8, 2],
       [2, 9, 1, 9, 8, 3, 8, 6, 6],
       [7, 6, 5, 8, 7, 8, 1, 7, 5],
       [4, 9, 2, 3, 8, 4, 8, 2, 8]], dtype=int32)

In [38]:
m1[:4]

array([[3, 2, 4, 2, 1, 9, 9, 4, 8],
       [9, 3, 6, 7, 8, 3, 3, 4, 4],
       [6, 5, 6, 9, 5, 6, 3, 6, 8],
       [6, 7, 6, 3, 9, 9, 4, 5, 6]], dtype=int32)

In [ ]:
m1[1:4, 1:3] #[rows,columns]

array([[3, 6],
       [5, 6],
       [7, 6]], dtype=int32)

In [42]:
m1

array([[3, 2, 4, 2, 1, 9, 9, 4, 8],
       [9, 3, 6, 7, 8, 3, 3, 4, 4],
       [6, 5, 6, 9, 5, 6, 3, 6, 8],
       [6, 7, 6, 3, 9, 9, 4, 5, 6],
       [4, 4, 3, 9, 3, 4, 9, 4, 4],
       [6, 9, 5, 1, 2, 3, 2, 8, 2],
       [2, 9, 1, 9, 8, 3, 8, 6, 6],
       [7, 6, 5, 8, 7, 8, 1, 7, 5],
       [4, 9, 2, 3, 8, 4, 8, 2, 8]], dtype=int32)

In [43]:
m1[3:8, 3:8]

array([[3, 9, 9, 4, 5],
       [9, 3, 4, 9, 4],
       [1, 2, 3, 2, 8],
       [9, 8, 3, 8, 6],
       [8, 7, 8, 1, 7]], dtype=int32)

#masking or filter in matrix. 

In [45]:
m1.shape

(9, 9)

In [46]:
id(m1)

3035556235664

In [47]:
type(m1)

numpy.ndarray

In [49]:
m1

array([[3, 2, 4, 2, 1, 9, 9, 4, 8],
       [9, 3, 6, 7, 8, 3, 3, 4, 4],
       [6, 5, 6, 9, 5, 6, 3, 6, 8],
       [6, 7, 6, 3, 9, 9, 4, 5, 6],
       [4, 4, 3, 9, 3, 4, 9, 4, 4],
       [6, 9, 5, 1, 2, 3, 2, 8, 2],
       [2, 9, 1, 9, 8, 3, 8, 6, 6],
       [7, 6, 5, 8, 7, 8, 1, 7, 5],
       [4, 9, 2, 3, 8, 4, 8, 2, 8]], dtype=int32)

In [48]:
m1 < 5

array([[ True,  True,  True,  True,  True, False, False,  True, False],
       [False,  True, False, False, False,  True,  True,  True,  True],
       [False, False, False, False, False, False,  True, False, False],
       [False, False, False,  True, False, False,  True, False, False],
       [ True,  True,  True, False,  True,  True, False,  True,  True],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [ True, False,  True, False, False,  True, False, False, False],
       [False, False, False, False, False, False,  True, False, False],
       [ True, False,  True,  True, False,  True, False,  True, False]])

In [52]:
m1[m1 < 5]     

array([3, 2, 4, 2, 1, 4, 3, 3, 3, 4, 4, 3, 3, 4, 4, 4, 3, 3, 4, 4, 4, 1,
       2, 3, 2, 2, 2, 1, 3, 1, 4, 2, 3, 4, 2], dtype=int32)

In [53]:
m1[m1<=5]

array([3, 2, 4, 2, 1, 4, 3, 3, 3, 4, 4, 5, 5, 3, 3, 4, 5, 4, 4, 3, 3, 4,
       4, 4, 5, 1, 2, 3, 2, 2, 2, 1, 3, 5, 1, 5, 4, 2, 3, 4, 2],
      dtype=int32)

In [54]:
m1[m1!=5]

array([3, 2, 4, 2, 1, 9, 9, 4, 8, 9, 3, 6, 7, 8, 3, 3, 4, 4, 6, 6, 9, 6,
       3, 6, 8, 6, 7, 6, 3, 9, 9, 4, 6, 4, 4, 3, 9, 3, 4, 9, 4, 4, 6, 9,
       1, 2, 3, 2, 8, 2, 2, 9, 1, 9, 8, 3, 8, 6, 6, 7, 6, 8, 7, 8, 1, 7,
       4, 9, 2, 3, 8, 4, 8, 2, 8], dtype=int32)

In [56]:
m1[m1==5]

array([5, 5, 5, 5, 5, 5], dtype=int32)

In [57]:
m1[m1>5]

array([9, 9, 8, 9, 6, 7, 8, 6, 6, 9, 6, 6, 8, 6, 7, 6, 9, 9, 6, 9, 9, 6,
       9, 8, 9, 9, 8, 8, 6, 6, 7, 6, 8, 7, 8, 7, 9, 8, 8, 8], dtype=int32)