Numpy

In [4]:
!pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.3 MB 3.9 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.3 MB 6.2 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.3 MB 8.2 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.3 MB 8.7 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.3 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 9.6 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 8.9 MB/s eta 0:00:00


In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.5'

In [4]:
my_list = [0, 1, 2, 3, 4, 5]
my_list         

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [8]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.arange(-20,10) #left argument has to be smaller than the right argument, otherwise it will return an empty array

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [19]:
print(np.zeros(3, dtype = float)) #1D array

[0. 0. 0.]


In [20]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [21]:
np.zeros([2,2]) #2D array, the first argument is the number of rows, the second argument is the number of columns. By default, the data type is float. We can change it to int by adding dtype = int as an argument.

array([[0., 0.],
       [0., 0.]])

In [22]:
np.zeros([10,10], dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
np.ones(4)

array([1., 1., 1., 1.])

In [24]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [31]:
np.random.rand(3)

array([0.224272  , 0.7936101 , 0.62448345])

In [34]:
np.random.rand(3,4)

array([[0.32708729, 0.33221576, 0.6654027 , 0.7211785 ],
       [0.65544078, 0.21007093, 0.23333337, 0.66940265],
       [0.96500189, 0.50660191, 0.94808562, 0.97724683]])

In [48]:
np.random.randint(3)

0

In [55]:
np.random.randint(20,30)

25

In [65]:
print(np.random.randint(1,10,4))

[7 1 1 7]


In [73]:
m = np.random.randint(1, 10, (4, 6))
print(m)

[[8 7 4 1 6 6]
 [9 9 8 3 1 7]
 [3 5 7 6 6 1]
 [8 1 7 4 5 9]]
