Array creation functions

In [1]:
import numpy as np

In [3]:
#Create an array from a list
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [5]:
#Create an array with evenly spaced values
b = np.arange(0, 10, 3)
print("Array b:", b)

Array b: [0 3 6 9]


In [6]:
d = np.zeros((2, 3))
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
d = np.zeros((2, 3), dtype=int)
print("Array d:\n", d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [8]:
e = np.ones((2, 3))
print("Array e:\n", e)

Array e:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#Create an identity matrix
f = np.eye(4) #4x4 identity matrix
print("Array f:\n", f)

Array f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Array Manipulation Functions

In [15]:
#Reshape an array
a1 = np.array([1, 2, 3])
reshaped = a1.reshape((1, 3)) #Reshape to 1 row and 3 columns
print("Reshaped array:\n", reshaped)

Reshaped array:
 [[1 2 3]]


In [14]:
#Reshape an array
a1 = np.array([1, 2, 3])
reshaped = a1.reshape((3, 1)) #Reshape to 3 row and 1 columns
print("Reshaped array:\n", reshaped)

Reshaped array:
 [[1]
 [2]
 [3]]


In [16]:
#Flatten an array
f1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
flattened = np.ravel(f1) #Flatten the array to 1D
print("Flattened array:\n", flattened)

Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10]


In [17]:
#Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1) #Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [18]:
#Stck arrays vertically
a2 = np.array([[1, 2], [3, 4]])
b2 = np.array([[5, 6], [7, 8]])
stacked = np.vstack((a2, b2)) #Stack vertically
print("Stacked array:\n", stacked)

Stacked array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#Stack arrays horizontally

Mathematical Functions

In [19]:
#Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2) #Add 2 to itself
print("Added array:\n", added)

Added array:
 [3 4 5 6]


In [20]:
#Square each element
squared = np.power(g,2) #Square each element
print("Squared array:\n", squared)

Squared array:
 [ 1  4  9 16]


In [21]:
#Square root of an array
sqr_root = np.sqrt(g) #Square root of each element
print("Square root array:\n", sqr_root)

Square root array:
 [1.         1.41421356 1.73205081 2.        ]


In [22]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [23]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [25]:
a3 = np.array([[1, 2, 3]])
dot_product = np.dot(a1, a) #Dot product of a3 and a1
print("Dot product:\n", dot_product)

Dot product:
 14


Statistical Functions

In [26]:
s = np.array([[1, 2, 3, 4]])
mean = np.mean(s) #Mean of the array
print("Mean of array s:", mean)

Mean of array s: 2.5


In [27]:
#Standard deviation of an array
var = np.var(s)
print("Variance of array s:", var)

Variance of array s: 1.25


In [28]:
#Standard deviation of an array
std_dev = np.std(s) #Standard deviation of the array
print("Standard deviation of array s:", std_dev)

Standard deviation of array s: 1.118033988749895


In [29]:
#Minimum and maximum of an array
min_val = np.min(s) #Minimum value in the array
max_val = np.max(s) #Maximum value in the array
print("Minimum value in array s:", min_val)
print("Maximum value in array s:", max_val)

Minimum value in array s: 1
Maximum value in array s: 4


Linear Algebra

In [30]:
matrix = np.array([[1, 2], [3, 4]])
matrix

array([[1, 2],
       [3, 4]])

Random Sampling Functions

In [ ]:
#Generate a random value
random_val = np.random.rand(3) #Random value between 0 and 3
print("Random value:\n", random_val)

Random value:
 [7.85550148e-05 6.29942438e-01 2.74468082e-01]


In [34]:
#Set seed for reproducibility
np.random.seed(42) 

random_val = np.random.rand(3) #Random value between 0 and 3
print("Random value with seed:\n", random_val)

Random value with seed:
 [0.37454012 0.95071431 0.73199394]


In [35]:
#Generate random integers
random_ints = np.random.randint(0, 10, size=5) #Random integers between 0 and 10
print("Random integers:\n", random_ints)

Random integers:
 [4 6 9 2 6]


In [36]:
#Set seed for reproducibility
np.random.seed(0) 

#Generate random integers
random_ints = np.random.randint(0, 10, size=5) #Random
print("Random integers with seed:\n", random_ints)

Random integers with seed:
 [5 0 3 3 7]


Boolean & Logical Functions

In [37]:
#Check if all elements are true

logical_test = np.array([True, True, False])
all_true = np.all(logical_test) #Check if all elements are true
print("Are all elements true?", all_true)

Are all elements true? False


In [38]:
logical_test2 = np.array([True, True, True])
all_true2 = np.all(logical_test2) #Check if all elements are true
print("Are all elements true?", all_true2)

Are all elements true? True


Set operations

In [ ]:
#Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])